### ISSUE TITLE
게시판 글 읽기 기능 구현

### ISSUE THREAD

**Issue by Damgom** [codestates-seb/seb39_main_024#11]
# 게시판 글 읽기 기능 구현
***
# todo
1. [x] 게시판 글 읽기 기능 구현
2. [ ] 다음 글 읽기 기능
3. [ ] 이전 글 읽기 기능
***
# deadline
- 220920
