### ISSUE TITLE
SC_VIDEO_02 

### ISSUE THREAD

**Issue by aoravel1212** [codestates-seb/seb39_main_024#27]
# todo
1. [x] 영상 디테일 화면 렌더링
2. [x] 영상 재생 기능
3. [x] 영상 목록 렌더링
4. [x] 영상 재생 시간 기록 기능
***
# deadline
- 220923
