### ISSUE TITLE
SC_POST_EDIT_01

### ISSUE THREAD

**Issue by aoravel1212** [codestates-seb/seb39_main_024#29]
# todo
1. [x] POST_EDIT_01 | 카테고리
2. [x] POST_EDIT_02 | 수정 완료 버튼
3. [x] POST_EDIT_03 | 제목 입력 폼
4. [x] POST_EDIT_04 | 사진 업로드 버튼
5. [x] POST_EDIT_05 | 사진 박스
6. [x] POST_EDIT_06 | 내용 수정 폼

***
# deadline
- 220927
