### ISSUE TITLE
SC_SIDEBAR_01

### ISSUE THREAD

**Issue by aoravel1212** [codestates-seb/seb39_main_024#32]
# todo
1. [ ] SIDEBAR_01 | 요약 버튼
2. [ ] SIDEBAR_02 | 캘린더 버튼
3. [ ] SIDEBAR_03 | 프로필 편집 버튼
4. [ ] SIDEBAR_04 | 회원 탈퇴 버튼

***
# deadline
- 220929
