### ISSUE TITLE
SC_MYPAGE_01 (요약)

### ISSUE THREAD

**Issue by aoravel1212** [codestates-seb/seb39_main_024#34]
# todo
아래 기능이 요약되어있는 대시보드 만들기
- [ ] MYPAGE_01 | 일일 운동 시간
- [ ] MYPAGE_02 | 목표 달성 스티커
- [ ] MYPAGE_03 | 운동 기록 캘린더

# deadline
- 220926
