### ISSUE TITLE
DB Mapping

### ISSUE THREAD

**Issue by Damgom** [codestates-seb/seb39_main_024#46]
# DB Mapping
***
# todo
1. [x] board-comment mapping
3. [x] board-category mapping
4. [x] board-member mapping
5. [x] comment-member mapping
***
# deadline
- 220930
