### ISSUE TITLE
역할분담

### ISSUE THREAD

**Issue by Damgom** [codestates-seb/seb39_main_024#7]
# 역할분담
***
# todo
1. [x] 개발환경 구성(dependency, package설정 등)
2. [x] 첫주차 개발할 파트 분배
3. [x] 분배한 파트 Issues 작성
***
# deadline
- 220915
