### ISSUE TITLE
개발환경구성

### ISSUE THREAD

**Issue by aoravel1212** [codestates-seb/seb39_main_024#9]
# todo
1. [x] 사용 기술 의논
2. [x] 필요한 라이브러리 설치
3. [x] 골격 만들기
4. [x] 담당 기능 분배
# deadline
- 22.09.18
